### ISSUE TITLE
Error from tags not being the same case

### ISSUE THREAD

**Issue by RockyKev** [11ty/eleventy-base-blog#103]
> Output conflict: multiple input files are writing to `_site/tags/javascript/index`. Use distinct `permalink` values to resolve this conflict.

I was able to identify what the error was, and recreate it by doing the following:
_(two separate posts. Note the `Javascript` and `javascript`)_

---
title: TIL about flattening a JS array
date: 2020-08-15
published: true
tags: ['Javascript', 'array']
---

---
title: TIL All the Javascript Sandboxes
date: 2020-08-07
published: true
tags: ['javascript', 'sandbox']
---

Not sure if the solution is to make them all lowercase, or create two separate tags like `Javascript` and `javascript`. 

Thank you so much!

**Comment by ijager** [comment]
I ran into the same error, accidentally filed it in the main repo: https://github.com/11ty/eleventy/issues/1942

**Comment by zachleat** [comment]
Yeah, unfortunately the best thing to say right now is to change your tags case sensitivity to match up.

Additional discussion continuing here, if you’d like to participate further! https://github.com/11ty/eleventy/issues/2462
