### ISSUE TITLE
How to add pagination to homepage and tag pages?

### ISSUE THREAD

**Issue by cawa-93** [11ty/eleventy-base-blog#129]
I would like add pagination to all `postlists`. For homepage i almost find solution. But how do it for tag pages?

**Comment by zachleat** [comment]
For archive.njk you just follow the standard pagination instructions (with `pagination` -> `data: collections.posts`). See https://www.11ty.dev/docs/pagination/#paging-a-collection

For tag pages you’ll have to get a bit more clever, read the two-layer pagination pinned issue on Eleventy core https://github.com/11ty/eleventy/issues/461

**Comment by ndaidong** [comment]
@cawa-93 could you add pagination to Archive page at the end? I'm learning 11ty and being stuck at this issue. The docs does not helpful.
