### ISSUE TITLE
Can not install and run on M1 Mac?

### ISSUE THREAD

**Issue by MattWilcox** [11ty/eleventy-base-blog#140]
Entirely possible I'm doing something wrong, but here's what I did:

- Clone this repo
- cd into it
- `npm install`
- `npx @11ty/eleventy`

This fails, with the output:

```
npx @11ty/eleventy
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] 1. Error in your Eleventy config file 'eleventy.config.js'. You may need to run `npm install`. (via EleventyConfigError)
[11ty] 2. Something went wrong installing the "sharp" module
[11ty] 
[11ty] Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
```

## Info

```
node --version
v18.13.0

npm --version
8.19.3
```

OSX 12.6.2 (Monterey), M1 Mac

**Comment by pdehaan** [comment]
Interesting, worked for me on my M1 Max; although I've had issues w/ Sharp in the past and might have `brew installed` some libraries in the past.

https://sharp.pixelplumbing.com/install#apple-m1 implies it "should work"

> Prebuilt sharp and libvips binaries have been provided for macOS on ARM64 since sharp v0.29.0.

```sh
npm ls sharp
eleventy-base-blog@8.0.0 /private/tmp/11ty-base-blog
└─┬ @11ty/eleventy-img@2.0.1
  └── sharp@0.30.7
```

Does <kbd>npm i sharp -D</kbd> work for you locally?

**Comment by MattWilcox** [comment]
I just deleted the `node_modules` and `package-lock.json`, then re-tried... and it worked.

**Comment by MattWilcox** [comment]
Yep, it's a weird one. Don't know quite how npm works, but maybe the source module was missing or corrupt when I initially tried. Thanks for the help, by the way!
