### ISSUE TITLE
How can I show the 10 latest posts instead of 3 in the home page?

### ISSUE THREAD

**Issue by verlok** [11ty/eleventy-base-blog#170]
Hello,
how can I show the 10 latest posts instead of 3 in the home page?

I couldn't find the number 3, neither in the eleventy config file, nor in the home page template.

Thanks

**Comment by bobmonsour** [comment]
On line 6 of this file, change the 3 to a 10.

https://github.com/11ty/eleventy-base-blog/blob/main/content/index.njk

**Comment by verlok** [comment]
Ok I must admit I had searched a little bit in a hurry 😓 

This is the answer:

```
numberOfLatestPostsToShow: 3
```

Thanks @bobmonsour for pointing out.
