### ISSUE TITLE
Set.add() takes a single argument?

### ISSUE THREAD

**Issue by pborenstein** [11ty/eleventy-base-blog#18]
I was looking at the changes in `getTagList.js`. Sets are new to me, so I went off to see how they work. As I understand it, `Set.prototype.add()` takes a single argument, so I don't think that `tagSet.add(...tags)` adds all the elements in `tags` to `tagSet` if that's what it's meant to do.

https://github.com/11ty/eleventy-base-blog/blob/002f4e2f2a66b863026253a41bf4df853f1e39d2/_11ty/getTagList.js#L23

Replace maybe with:

```js
tags.forEach(t => tagSet.add(t))
```

**Comment by mathiasbynens** [comment]
My bad! That's what I get for submitting patches using the GitHub web UI without testing properly :blush: 

Patch: https://github.com/11ty/eleventy-base-blog/pull/19

**Comment by zachleat** [comment]
wait, who merged it though

_runs away_ 🏃

**Comment by zachleat** [comment]
Found one more typo there but we should be good now 😅
