### ISSUE TITLE
v9: Node.js disagreement betweeen .nvmrc (20) and package.json (18)

### ISSUE THREAD

**Issue by rdela** [11ty/eleventy-base-blog#183]
Node.js 20 here
https://github.com/11ty/eleventy-base-blog/blob/ffa7c673cd4b9fb999596e97dc8b5b11073fa594/.nvmrc#L1

Node.js 18 here
https://github.com/11ty/eleventy-base-blog/blob/ffa7c673cd4b9fb999596e97dc8b5b11073fa594/package.json#L27

**Comment by zachleat** [comment]
Hmm—is that a problem?

18 is the minimum—20 is the current preferred. I wouldn’t mind upgrading to 22 in the `.nvmrc` but wouldn’t change the `engines` in `package.json`—unless I’ve misunderstood something!

**Comment by rdela** [comment]
Makes sense to me. Pointed it out in case it was an oversight. Nothing in the docs suggests otherwise: 

https://github.com/nvm-sh/nvm?tab=readme-ov-file#nvmrc 

https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#engines

**Comment by rdela** [comment]
22 becomes active LTS on 29 Oct https://github.com/nodejs/Release?tab=readme-ov-file#release-schedule
