### ISSUE TITLE
With EleventyTransform, images need to be in `/content`; can't use the existing `/public/img` directory

### ISSUE THREAD

**Issue by DianaPerkinsDesign** [11ty/eleventy-base-blog#189]
The base blog includes a `/public/img` directory, but now that it uses [EleventyTransform](https://github.com/11ty/eleventy-img/blob/24305ac9b5298e2685e5d885d078c4b29a4fb513/src/util.js#L56), images need to be in the input directory (in this repo's case: `/content`), and will return an error if you use `/public/img`:

```
[11ty] 1. Having trouble writing to "./_site/tags/index.html" from "./content/tags.njk" (via EleventyTemplateError)
[11ty] 2. Transform `@11ty/eleventy/html-transformer` encountered an error when transforming ./content/tags.njk. (via EleventyTransformError)
[11ty] 3. ENOENT: no such file or directory, stat 'content/img/burger-look.png'
```

<sub>Obligatory: apologies if I just don't understand the new way of doing things, and feel free to close if that's the case 😅</sub>

**Comment by DianaPerkinsDesign** [comment]
Closing because I guess it's intended just for images that you call via CSS? Feels strange to separate them like that, but I'm game to give it a go 👍

**Comment by cfuendev** [comment]
New to Eleventy v3 and I sincerely couldn't figure why my images weren't loading or why only the the url in my images `src/` was being prepended with `content/`
