### ISSUE TITLE
Avoid the “dates off by one day” pitfall

### ISSUE THREAD

**Issue by mathiasbynens** [11ty/eleventy-base-blog#30]
It looks like https://github.com/11ty/eleventy-base-blog/blob/1148b90e22851df01be3f6b8b9ee6522c0b0566b/_includes/postslist.njk#L5 runs into the [“dates off by one day” pitfall](https://www.11ty.io/docs/dates/#dates-off-by-one-day). Anyone willing to contribute a fix?

**Comment by zachleat** [comment]
Ah, is this still true? Looks like we use `luxon` to assume UTC. https://github.com/11ty/eleventy-base-blog/blame/master/.eleventy.js#L19

`DateTime.fromJSDate(dateObj, {zone: 'utc'});` outputs `2018-09-30T00:00:00.000Z`

and

`DateTime.fromJSDate(dateObj, {zone: 'utc'}).toFormat("z");` outputs `UTC`

**Comment by zachleat** [comment]
Double double checked that this seems to be working fine. Closing for now!
