### ISSUE TITLE
Look at publishing a JSON feed

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-base-blog#35]
https://twitter.com/zachleat/status/1142099561558753285

Related https://github.com/11ty/eleventy-plugin-rss

**Comment by zachleat** [comment]
Shipped! example also added https://github.com/11ty/eleventy-plugin-rss

**Comment by brycewray** [comment]
> Shipped! example also added https://github.com/11ty/eleventy-plugin-rss

@zachleat (et al.): If one wanted to come up with an .11ty.js version of this, any thoughts on how to translate the ```dump | safe``` filtering (particularly the `dump` part) in the following line from the supplied Nunjucks version?

```js
"content_html": {% if post.templateContent %}{{ post.templateContent | dump | safe }}{% else %}""{% endif %}
```
