### ISSUE TITLE
Document dependency on Apache

### ISSUE THREAD

**Issue by mathiasbynens** [11ty/eleventy-base-blog#4]
The demo depends on `feed/.htaccess` being applied, which is not true on gh-pages. The dependency on Apache should be documented. It would be even better if there was a way to avoid this dependency on any specific server.

**Comment by zachleat** [comment]
Hmm, dang. Well, I _really_ like directory urls per the recommendations in https://www.w3.org/Provider/Style/URI.html

But in the interest of keeping it server agnostic, I’ll point to the atom.xml file instead.

I think I’ll leave the .htaccess file in there in case someone wants to use it though (me)? Hopefully this isn’t confusing.
