### ISSUE TITLE
Post List Numbering : Question

### ISSUE THREAD

**Issue by ng-chicago** [11ty/eleventy-base-blog#47]
Is it possible to show the numbering for all of your posts instead of just the number is shown on the home page?
So if you have 57 posts, but are only showing the 3 most recent, the numbering would be

3 Latest Posts
  57  blah blah
  56  blah blah
  55  blah blah

More posts in the archive.

**Comment by zachleat** [comment]
A ha! I have added this to the `eleventy-base-blog` repo on the index page. I added a `postslistCounter` variable that does it: https://github.com/11ty/eleventy-base-blog/blob/03bb550d4698c8db48d86195cca597a72e43269b/index.njk#L11

**Comment by zachleat** [comment]
You can see how it’s used inside of the `include` here: https://github.com/11ty/eleventy-base-blog/blob/03bb550d4698c8db48d86195cca597a72e43269b/_includes/postslist.njk#L1
