### ISSUE TITLE
Disappearing trailing slash

### ISSUE THREAD

**Issue by mathiasbynens** [11ty/eleventy-base-blog#5]
The source of https://11ty.github.io/eleventy-base-blog/ contains:

```html
<link rel="alternate" href="/eleventy-base-blog/feed" type="application/atom+xml" title="">
 ```

The trailing slash is missing. https://github.com/11ty/eleventy-base-blog/blob/6c2983e013b70efeed7277b7c2382958cb0cdbcb/_includes/layouts/base.njk#L9 Does `| url` remove it?

**Comment by zachleat** [comment]
Thank you!
