### ISSUE TITLE
Add skip to content link

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-base-blog#51]
As noted was necessary in #50.

**Comment by zachleat** [comment]
Nice pattern on https://a11yproject.com/patterns/

**Comment by mvllow** [comment]
Ciao! Was about to work on this and noticed there seems to already be a skip to content link above the header:

https://github.com/11ty/eleventy-base-blog/blob/851eafdc4c3a612142e0e6ae84f54cb0f0eb98b1/_includes/layouts/base.njk#L43

I believe this issue can be closed :)

**Comment by zachleat** [comment]
Ah yes, appreciate the update!
