### ISSUE TITLE
How best to pull updates of this repo into my fork?

### ISSUE THREAD

**Issue by francisbarton** [11ty/eleventy-base-blog#52]
I tried to work out how to update my eleventy blog, forked from here, with any fixes and new features. I'm not sure I did it the right way, and I would like some guidance on how best to get updates without having merge conflict hell.

It's not clear to me where best to ask for this kind of advice and support with eleventy, so I wrote it all up as a StackOverflow question [here](https://stackoverflow.com/questions/59592328/what-is-the-recommended-way-of-getting-the-latest-updates-from-upstream-eleventy).

Happy to close this issue if not appropriate, or if I get some good advice from SO then maybe that could be included in the eleventy-base-blog docs.

**Comment by zachleat** [comment]
I see some chatter on that StackOverflow question—did that answer it for you?

Otherwise I’d recommend filing a Discussion item here: https://github.com/11ty/eleventy/discussions
