### ISSUE TITLE
Move content pages into subdirectory?

### ISSUE THREAD

**Issue by autonome** [11ty/eleventy-base-blog#55]
Having the pages in the root directory vs a subdirectory feels messy to me, so I'd like to move into _pages.

However, once I do that for all .njk and other content files, and update the `input` path in .eleventy.js to `input: "_pages"`, I get this error:

> Problem writing Eleventy templates:
> TemplateLayoutPathResolver directory does not exist for layouts/home.njk: _pages/_includes

Any tips on what path I need to update where to get this config working?

**Comment by autonome** [comment]
Hm, I'd rather not have _includes as a subdirectory of _pages, but I tried it anyway, and got new+different errors.

**Comment by SteveALee** [comment]
+1 I moved all mine to `/src` and and added `_layouts` as a peer of `_includes`

**Comment by zachleat** [comment]
Unfortunately for now `_includes` must be in your input directory. Read https://www.11ty.dev/docs/config/#directory-for-includes

This is likely to change, follow along at https://github.com/11ty/eleventy/issues/67
