### ISSUE TITLE
Missing code?

### ISSUE THREAD

**Issue by SteveALee** [11ty/eleventy-base-blog#62]
The [comments here](https://github.com/11ty/eleventy-base-blog/blob/master/.eleventy.js#L78-L86) don't quite make sense. 

It seems a line of code has been removed.

**Comment by zachleat** [comment]
Ah sorry it looks like your link is not accurate. Can you update it? (if you hit `y` on the code page on GitHub it will create a direct link to the commit that won’t break if the file changes)

**Comment by SteveALee** [comment]
Neat trick.

https://github.com/11ty/eleventy-base-blog/blob/d28f834fbb285ea45de17078d1e575b5f6dc1d2a/.eleventy.js#L109-L117

But I now see the setting the comments refer to is actually the last line in the comments. I missed it. Perhaps add a black line so it stands out?

**Comment by zachleat** [comment]
Pushed some additional comments and formatting to that config file—hopefully helpful!
