### ISSUE TITLE
Eleventy + Contentful

### ISSUE THREAD

**Issue by danpantinople** [11ty/eleventy-base-blog#65]
Hi, so sorry I had to post here. I'm not too good with JS. I just need help setting up contentful on this. I've already connected contentful but how do I have my contentful posts populate the posts collection?

**Comment by shanerobinson** [comment]
This example uses DatoCMS and it's GraphQL API with 11ty, but the concept would be the same with Contentful's GraphQL API: https://www.webstoemp.com/blog/headless-cms-graphql-api-eleventy/

**Comment by zachleat** [comment]
Poke around in the starters, there are a few that mention Contentful! https://www.11ty.dev/docs/starter/
