### ISSUE TITLE
Case sensitivity of tags

### ISSUE THREAD

**Issue by pde** [11ty/eleventy-base-blog#71]
Currently, the tags in the base blog are case sensitive. I suspect that that's not what most users would expect or want. Would be great to add a config option to control this. Perhaps defaulting to case insensitivity?

**Comment by zachleat** [comment]
Hmm, this is an interesting question. By default in JavaScript object keys are case sensitive. I think this should probably be a Discussion item here so more people can weigh in: https://github.com/11ty/eleventy/discussions
