### ISSUE TITLE
No whitespace left between tags in post.njk when styles are disabled

### ISSUE THREAD

**Issue by siimpragi** [11ty/eleventy-base-blog#94]
I noticed a minor issue with the `post.njk` layout. Leading and trailing whitespace is stripped from the `.post-tag` anchor elements. As a result, when styles are disabled, these elements run against each other.

![tag-spacing](https://user-images.githubusercontent.com/8535926/113216885-ac107f00-9285-11eb-96ff-89142f459400.png)

This doesn't happen to tags in other layouts where some whitespace is preserved.

Could the solution be to allow some whitespace and wrap these `<time>` and `<a>`-s in `post.njk` in a flex container? Maybe this way, when styles are enabled, [we avoid getting " " + element's margin](https://css-tricks.com/fighting-the-space-between-inline-block-elements/#just-use-flexbox-instead).

P.S. Eleventy is awesome! 😄 This template is a great starting point.

**Comment by zachleat** [comment]
I fixed this one! Make sure you’re familiar with https://mozilla.github.io/nunjucks/templating.html#whitespace-control too

Personally I like to use `{%-` at the beginning and `%}` at the end of tags
